server:
  port: 8081

spring:
  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: "*"
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

test:
  client:
    address:
      url: http://localhost:8082/addresses

